aziz
3amekaziz
In a call

aziz — 3/2/2026 11:20 PM
1311422356
Scarab — 3/4/2026 3:41 PM
https://windsurf.com/refer?referral_code=rr1pilnc9helve1l
Referrals | Windsurf
Refer a friend and earn bonus add-on prompt credits.
Referrals | Windsurf
Scarab — 3/4/2026 4:04 PM
https://windsurf.com/refer?referral_code=rr1pilnc9helve1l
Referrals | Windsurf
Refer a friend and earn bonus add-on prompt credits.
Referrals | Windsurf
aziz — 3/4/2026 4:40 PM
1311422356
Scarab — 3/4/2026 10:57 PM
✘ [ERROR] Could not resolve "chart.js/auto"

    src/app/admin/pages/analytics/analytics.component.ts:4:18:
      4 │ import Chart from 'chart.js/auto';
        ╵                   ~~~~~~~~~~~~~~~

message.txt
1 KB
Scarab — 3/4/2026 11:07 PM
npm install chart.js
Scarab — Yesterday at 12:38 AM
ALTER TABLE donations
ADD COLUMN item_condition VARCHAR(50) NOT NULL;
message.txt
1 KB
Scarab — Yesterday at 12:55 AM
item_name
ALTER TABLE donations
ADD COLUMN item_name VARCHAR(50) NOT NULL;
Scarab — 11:17 PM
spring.application.name=ABONNEMENT-SERVICE
server.port=8085

# =================================
# DATABASE
# =================================

message.txt
2 KB
﻿
Scarab
lnni_
 
random stuff ..👁️
spring.application.name=ABONNEMENT-SERVICE
server.port=8085

# =================================
# DATABASE
# =================================

spring.datasource.url=jdbc:postgresql://localhost:5432/abonnements
spring.datasource.username=aziz
spring.datasource.password=aziz123
spring.datasource.driver-class-name=org.postgresql.Driver

# =================================
# JPA
# =================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =================================
# EMAIL
# =================================

spring.mail.host=ssl0.ovh.net
spring.mail.port=587
spring.mail.username=mino.support@minolingo.online
spring.mail.password=mr?FAtB2AUP&i2b
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# =================================
# APP CONFIG
# =================================

app.platform.name=MiNoLingo
app.support.email=mino.support@minolingo.online
app.frontend.url=https://minolingo.online

# =================================
# STRIPE
# =================================

stripe.secret.key=sk_test_51T4Qw2JR9fwPcov6JC12Q0FBdH3LDTwZpYTCOh1nlxg9HW1GqNtENnjZoQiK6SmICZCxXyQwzFStjL5YytAH0yTQ00QeJvQZhz
stripe.public.key=pk_test_51T4Qw2JR9fwPcov6SVVfuVLSwnbSuk3SXNnfiMfCi20In3V9EcEiBsyA2U4ZrAYjENuYk52nVcy89SQXQZUW5WyR00oDtmpXLs

# =================================
# FEIGN CLIENT
# =================================
feign.user-service.url=http://localhost:8090

# =================================
# EUREKA CLIENT
# =================================

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

